name: snowpark_xgboost_tpc
channels:
dependencies:
  - pip:    
    - pynytimes
    - pillow
<<<<<<< HEAD
    - movieposters
=======
    - movieposters
    - IMDbPY
    - plotly
    - ntlk
>>>>>>> 4aa9d9a8e81882dad2ff77776b0a0c6639196a40
